name: crash_box
description: "A BOX CRASHED"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.2.0
  flutter_screenutil: ^5.8.4
  dio: ^5.3.2
  install_plugin: ^2.1.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  logger: ^2.0.2+1
  url_launcher: ^6.2.3
  date_format: ^2.0.7
  fl_chart: ^0.66.0
  flutter_smart_dialog: ^4.9.6
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8

  bruno: ^3.4.3
  getwidget: ^4.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/